### ISSUE TITLE
Get all administrators

### ISSUE THREAD

**Issue by ajunge** [OpenVASP/openvasp-contracts#12]
It would be convenient to have a function to get all the administrators. Right now it can be obtained by parsing all the `AdministratorAdded` and `AdministratorRemoved` but it seems to be a little overhead.

Is there a security constraint on this?

**Comment by PaterSantyago** [comment]
It can be done, via low-level methods, inherited from `AccessControl` smart contract from OpenZeppelin library. You can find additional details [here](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/access/AccessControl.sol).

**Comment by ajunge** [comment]
Ok. Thanx. Closing
