### ISSUE TITLE
Erroneous Credentials insertion

### ISSUE THREAD

**Issue by dspicher** [OpenVASP/openvasp-contracts#37]
According to [OVIP12](https://github.com/OpenVASP/ovips/blob/f4de559c0a366c7d4a9afab5243b2ce227239120/ovip-0012.md), `getCredentialsRef` should return "the transaction id with which the Credentials were inserted" and "the Keccak256 hash of the credentials".

However, currently the transaction hash is not stored during `insertCredentials`. For retrieval, the first return value from above is just the [encoded version](https://github.com/OpenVASP/openvasp-contracts/blob/master/contracts/VASPDirectory.sol#L97) of the second return value.

How is it possible to retrieve the credentials themselves like this?

**Comment by Felix0301** [comment]
Smart contracts are implemented correctly - ovip-0012 was not updated correctly => solved by https://github.com/OpenVASP/ovips/commit/7088efa3dfadd4efa95995199ecc6e3283a18fdc

**Comment by dspicher** [comment]
Then how are the credentials actually fetched? Do I have to go through the event logs?
